#!/bin/sh

mkdir -p static
cp src/cli.js static/
elm make --optimize src/Main.elm --output=static/main.js
# xmlhttprequest is part of the browser api but not by default available via node
# so we have to install it with npm install xmlhttprequest
# but also we have to require it in the js code generated by the elm compiler
sed -i '1s/^/var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;\n/' static/main.js
# There is a bug in the  xmlhttprequest library:
# https://github.com/driverdan/node-XMLHttpRequest/issues/184
# So we just have to change the generated js code to use the 'wrong' attribute.
sed -i 's/toBody(xhr.response)/toBody(xhr.responseText)/' static/main.js
